INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('AGRICULTOR','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('ALBAÑIL','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('AMA DE CASA','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('BOMBERO','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('CAJERO','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('CAMBISTA','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('CARNICERO','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('CARPINTERO','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('COMERCIANTE','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('CRIADOR','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('EBANISTA','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('ELECTRICISTA','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('ESTILISTA','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('ESTUDIANTE','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('FONTANERO','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('LAVANDERO','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('LIMPIADOR','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('MENSAJERO','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('MONTADOR DE ESTRUCTURAS METÁLICAS','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('OBRERO','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('OFICINISTA','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('OPERADOR DE MÁQUINARIA','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('ORFEBRE','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('PANADERO','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('PEÓN','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('PESCADOR','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('PINTOR','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('POLICIA','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('PROFESOR','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('RECEPCIONISTA','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('REPARTIDOR','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('SASTRE','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('SOLDADOR','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('TAXISTA','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('TRANSPORTISTA','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('VENDEDOR AMBULANTE','','ACTIVO')
INSERT INTO Ocupacion (Nombre, Descripcion, Estado) VALUES ('ZAPATERO','','ACTIVO')

