INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Paciente')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Cita')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Doctor(a)')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Enfermero(a)')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Técnico(a)')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Administrativo')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Historia Clínica Completa')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Historia Clínica')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Formulario HIS')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Disponibilidad')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Área')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Especialidad Médica')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Pabellón')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Consultorio')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Modo de Ingreso')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Tipo de Documento')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Ocupación')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Religión')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Idioma')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Etnia')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'País')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'CPT')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Laboratorio')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Financiador de Salud')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Unidad Productora de Servicios')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Horarios')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Perfil')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Auditoría')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Respaldar')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Restaurar')
INSERT INTO MenusxPerfil(IdPerfil, Menu)
VALUES(1, 'Triaje')