INSERT INTO FinanciadorSalud (Codigo, Nombre, Descripcion, Estado) VALUES ('1','USUARIO','','ACTIVO')
INSERT INTO FinanciadorSalud (Codigo, Nombre, Descripcion, Estado) VALUES ('2','SEGURO INTEGRAL (SIS)','','ACTIVO')
INSERT INTO FinanciadorSalud (Codigo, Nombre, Descripcion, Estado) VALUES ('3','ESSALUD','','ACTIVO')
INSERT INTO FinanciadorSalud (Codigo, Nombre, Descripcion, Estado) VALUES ('4','SOAT','','ACTIVO')
INSERT INTO FinanciadorSalud (Codigo, Nombre, Descripcion, Estado) VALUES ('5','SANIDAD FAP','','ACTIVO')
INSERT INTO FinanciadorSalud (Codigo, Nombre, Descripcion, Estado) VALUES ('6','SANIDAD NAVAL','','ACTIVO')
INSERT INTO FinanciadorSalud (Codigo, Nombre, Descripcion, Estado) VALUES ('7','SANIDAD EP','','ACTIVO')
INSERT INTO FinanciadorSalud (Codigo, Nombre, Descripcion, Estado) VALUES ('8','SANIDAD PNP','','ACTIVO')
INSERT INTO FinanciadorSalud (Codigo, Nombre, Descripcion, Estado) VALUES ('9','PRIVADOS','','ACTIVO')
INSERT INTO FinanciadorSalud (Codigo, Nombre, Descripcion, Estado) VALUES ('10','OTROS','','ACTIVO')
INSERT INTO FinanciadorSalud (Codigo, Nombre, Descripcion, Estado) VALUES ('11','EXONERADO','','ACTIVO')