insert into Ventana (Nombre) values ('Paciente')
insert into Ventana (Nombre) values ('Cita')
insert into Ventana (Nombre) values ('Consulta')
insert into Ventana (Nombre) values ('Doctor')
insert into Ventana (Nombre) values ('Enfermero')
insert into Ventana (Nombre) values ('Técnico')
insert into Ventana (Nombre) values ('Administrativo')
insert into Ventana (Nombre) values ('Historia Clínica Completa')
insert into Ventana (Nombre) values ('Historia Clínica')
insert into Ventana (Nombre) values ('Formulario HIS')
insert into Ventana (Nombre) values ('Áreas')
insert into Ventana (Nombre) values ('Especialidades Médicas')
insert into Ventana (Nombre) values ('Horario')
insert into Ventana (Nombre) values ('Perfil')
insert into Ventana (Nombre) values ('Auditoría')
insert into Ventana (Nombre) values ('Respaldo')